version: '3.8'

services:
  localstack:
    image: localstack/localstack
    networks:
      - bandmates-backend
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,s3
      - PERSISTENCE=1

  user-service:
    build: ./user-service
    depends_on:
      - localstack
    networks:
      - bandmates-backend
    ports:
      - "8080:8080"
    environment:
      - LOCALSTACK_HOSTNAME=localstack
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test

networks:
  bandmates-backend:
    driver: bridge
