version: '3.8'

services:
  localstack:
    image: localstack/localstack-pro
    networks:
      - bandmates-backend
    ports:
      - "4566:4566"
    environment:
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
      - SERVICES=dynamodb,s3, cognito-idp
      - PERSISTENCE=1

  auth-service:
    build: ./auth-service
    depends_on:
      - localstack
    networks:
      - bandmates-backend
    ports:
      - "8080:8080"
    environment:
      - LOCALSTACK_HOSTNAME=localstack
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - USER_POOL_NAME=${USER_POOL_NAME}
      - CLIENT_NAME=${CLIENT_NAME}

  post-service:
    build: ./post-service
    depends_on:
      - localstack
    networks:
      - bandmates-backend
    ports:
      - "8090:8090"
    environment:
      - LOCALSTACK_HOSTNAME=localstack
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test


  profile-service:
    build: ./profile-service
    depends_on:
      - localstack
    networks:
      - bandmates-backend
    ports:
      - "8081:8081"
    environment:
      - LOCALSTACK_HOSTNAME=localstack
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test

  gig-service:
    build: ./gig-service
    depends_on:
      - localstack
    networks:
      - bandmates-backend
    ports:
      - "8082:8082"
    environment:
      - LOCALSTACK_HOSTNAME=localstack
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - USER_POOL_NAME=${USER_POOL_NAME}
      - CLIENT_NAME=${CLIENT_NAME}

  group-service:
    build: ./group-service
    depends_on:
      - localstack
    networks:
      - bandmates-backend
    ports:
      - "8088:8088"
    environment:
      - LOCALSTACK_HOSTNAME=localstack
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - USER_POOL_NAME=${USER_POOL_NAME}
      - CLIENT_NAME=${CLIENT_NAME}

networks:
  bandmates-backend:
    driver: bridge
