name: Unified CI/CD Pipeline for Multiple Services

on:
  push:
    branches:
      - main
    paths:
      - 'auth-service/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: ['auth-service']
        include:
          - service: 'auth-service'
            path: 'auth-service'
            ecr_repo: 'auth-service'
            eb_env: 'Auth-service-env'
            eb_app: 'auth-service'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push Docker image to Amazon ECR
      run: |
        TIMESTAMP=$(date +%Y%m%d%H%M%S)
        IMAGE_TAG=${{ steps.login-ecr.outputs.registry }}/auth-service:$TIMESTAMP
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
        docker build -t $IMAGE_TAG ./${{ matrix.path }}
        docker push $IMAGE_TAG

    - name: Prepare Dockerrun.aws.json
      run: |
        jq --arg image "$IMAGE_TAG" '.Image.Name = $image' ./Dockerrun.aws.json > temp.json && mv temp.json ./Dockerrun.aws.json

    - name: Deploy Docker image to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v18
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: us-east-1
        application_name: ${{ matrix.eb_app }}
        environment_name: ${{ matrix.eb_env }}
        version_label: ${{ github.sha }}
        deployment_package: ./Dockerrun.aws.json
