name: CI/CD Pipeline for Profile Service

on:
  push:
    branches:
      - main
    paths:
      - 'profile-service/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      id: login-ecr

    - name: Build, tag, and push Docker image to Amazon ECR
      run: |
        docker build ./profile-service -t ${{ steps.login-ecr.outputs.registry }}/profile-service:${{ github.sha }} -t ${{ steps.login-ecr.outputs.registry }}/profile-service:latest
        docker push -a ${{ steps.login-ecr.outputs.registry }}/profile-service

    - name: Generate deployment package
      run: |
        cd profile-service
        zip ../deploy-profile.zip Dockerrun.aws.json

    - name: Deploy Docker image to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: us-east-1
        application_name: profile-service
        environment_name: Profile-service-env
        version_label: ${{ github.sha }}
        deployment_package: deploy-profile.zip
        use_existing_version_if_available: true
